syntax = "proto3";

package notes;

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/Ajay01103/go-notion/notes/gen/pb;pb";

message Note {
  string id = 1;
  string workspace_id = 2;
  string title = 3;
  string created_by = 4;
  bool is_private = 5;
  google.protobuf.Timestamp created_at = 6;
  google.protobuf.Timestamp updated_at = 7;
}

message CreateNoteRequest {
  string workspace_id = 1;
  string title = 2;
  bool is_private = 3;
}

message GetNoteRequest {
  string note_id = 1;
}

message ListWorkspaceNotesRequest {
  string workspace_id = 1;
}

message ListWorkspaceNotesResponse {
  repeated Note notes = 1;
}

message AppendNoteUpdateRequest {
  string note_id = 1;
  bytes data = 2;
}

service NotesService {
  rpc CreateNote(CreateNoteRequest) returns (Note);
  rpc GetNote(GetNoteRequest) returns (Note);
  rpc ListWorkspaceNotes(ListWorkspaceNotesRequest) returns (ListWorkspaceNotesResponse);
  rpc AppendNoteUpdate(AppendNoteUpdateRequest) returns (google.protobuf.Empty);
}
